Consolidate x-plat integration tests
dotnet/Nerdbank.GitVersioning pull request #528
Opened 2020-10-27 11:04 UTC by qmfrederik

Use a build matrix to avoid repeating the same code.

2020-10-27 12:41 UTC, qmfrederik commented
@AArnott The Windows failure looks unrelated, could you restart the job?

2020-10-31 15:39 UTC, AArnott requested changes
Thanks.

2020-10-31 15:39 UTC, AArnott commented on azure-pipelines.yml
> +          containerImage: 'disco-3.0'
copy paste error. this should be `archlinux`. This caused a failure in AzP.

2020-10-31 15:39 UTC, AArnott commented on azure-pipelines.yml
> +    - template: azure-pipelines/xplattest-pipeline.yml
nit: trailing EOL

2020-10-31 15:39 UTC, AArnott commented on azure-pipelines.yml
> +          containerImage: 'xenial'
nit: remove unnecessary single-quotes

2020-10-31 15:39 UTC, AArnott commented on azure-pipelines.yml
> +          installGit: 'sudo apt update && sudo apt-get install -y git'
nit: `installGit` does more than just install git in some cases. Maybe call it `bashSetup`?

2020-10-31 21:43 UTC, merged