Add `tagName` option to customize generated tag name
dotnet/Nerdbank.GitVersioning pull request #875
Opened 2022-12-15 16:04 UTC by ronaldbarendse

This fixes https://github.com/dotnet/Nerdbank.GitVersioning/issues/874 by adding a new option to the `version.json` file to allow customizing the generated tag name, defaulting to:
```json
{
  "tagName": "v{version}"
}
```

This default value is the same as was hardcoded before (see linked issue). resulting in the same output:
```
❯ nbgv tag
v11.0.0-alpha tag created at e9733c696af583dc2d1e988ce9b9dbbdada70596.
Remember to push to a remote: git push origin v11.0.0-alpha
```

Changing this option to e.g. `release-{version}` will result in the following output:
```
❯ nbgv tag
release-11.0.0-alpha tag created at fdb649066fb8a855660844c345b9a905034ca6b6.
Remember to push to a remote: git push origin release-11.0.0-alpha
```

2022-12-15 16:05 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/Nerdbank.GitVersioning?pullRequest=875) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/Nerdbank.GitVersioning?pullRequest=875) before we can accept your contribution.<br/><br/>:x: ronaldbarendse [sign now](https://cla.dotnetfoundation.org/dotnet/Nerdbank.GitVersioning?pullRequest=875)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/Nerdbank.GitVersioning?pullRequest=875) it.</sub>

2022-12-16 02:22 UTC, AArnott requested changes
Thanks for putting this together. I'm willing to merge, but can you address the few minor issues I call out?

2022-12-16 02:22 UTC, AArnott commented on src/NerdBank.GitVersioning/version.schema.json
> +        },
Can you move this into the `release` object? I get that tags aren't exactly within the realm of `nbgv release`, but it's *very* close, and the rest of this file is related to other things.

2022-12-16 02:22 UTC, AArnott commented on src/NerdBank.GitVersioning/VersionOptions.cs
> +    public string? TagNameOrDefault => this.TagName ?? DefaultTagName;
Drop the `?` nullable annotation from this property, as it is guaranteed to not return null.

2022-12-16 02:22 UTC, AArnott commented on src/NerdBank.GitVersioning/version.schema.json
> +          "pattern": ".*\\{version\\}.*",
Nit: you can drop the wildcards on either side because you're not using `^` and `$` anyway, so a match is already assumed to be somewhere in the middle.
```suggestion
          "pattern": "\\{version\\}",
```

2022-12-19 20:07 UTC, ronaldbarendse commented on src/NerdBank.GitVersioning/version.schema.json
> +          "pattern": ".*\\{version\\}.*",
I copied this pattern from the `branchName` property, but I'll change both to use the less verbose syntax 👍🏻

2022-12-19 20:16 UTC, ronaldbarendse commented
> Thanks for putting this together. I'm willing to merge, but can you address the few minor issues I call out?

No problem at all, thanks for creating and maintaining this tool! I've addressed all the things you pointed out, so should be good to merge if everything tests out correctly 😄

2023-01-28 17:14 UTC, AArnott approved these changes
Thanks again.

2023-01-28 17:15 UTC, merged