Add support for `NBGV_ThisAssemblyNamespace` property.
dotnet/Nerdbank.GitVersioning pull request #911
Opened 2023-03-20 11:53 UTC by alexrp

#555

2023-03-20 11:53 UTC, alexrp commented
@AArnott How do you feel about the approach here?

Also, how would you suggest I test this? I'm not really familiar with NBGV's test harness.

2023-03-20 14:00 UTC, AArnott commented
@KalleOlaviNiemitalo MSBuild does not distinguish between null or an empty string as property values, nor an unset value vs. a value set to an empty string. An MSBuild task property that is set to an msbuild property will never be null.

2023-03-20 14:06 UTC, AArnott commented
The PR looks ineffective for the other languages as well, since only F# emits a namespace. The other languages just no-op for the emit namespace instruction.

2023-03-20 14:09 UTC, AArnott requested changes
@alexrp you can add the tests to [this file](https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/test/Nerdbank.GitVersioning.Tests/AssemblyInfoTest.cs). Please test all the languages. There is already a test for each language, so leave those alone I suppose but duplicate them with your optional property set.
Please make sure the task works properly given task inputs that are set to the empty string (indicating the msbuild property is not set).

2023-03-20 14:19 UTC, alexrp commented
> The PR looks ineffective for the other languages as well, since only F# emits a namespace. The other languages just no-op for the emit namespace instruction.

Not sure I follow here. There's code to emit namespaces for all of them. It's just that the F# case is handled specially in `EmitNamespaceIfRequired()`.

2023-03-20 14:20 UTC, alexrp commented on src/Nerdbank.GitVersioning.Tasks/AssemblyVersionInfo.cs
> +                this.generator.EmitNamespaceIfRequired(this.ThisAssemblyNamespace ?? this.RootNamespace ?? "AssemblyInfo");
So is the conclusion that this should be changed to use `string.IsNullOrEmpty()` for both of these properties?

2023-03-20 16:00 UTC, AArnott commented on src/Nerdbank.GitVersioning.Tasks/AssemblyVersionInfo.cs
> +                this.generator.EmitNamespaceIfRequired(this.ThisAssemblyNamespace ?? this.RootNamespace ?? "AssemblyInfo");
Ya, that would probably be appropriate.

2023-03-20 16:03 UTC, AArnott commented
> There's code to emit namespaces for all of them. 

No, I don't think so. The tests themselves prove that no namespace is emitted for C# or VB, but there is for F#. Issue #555 was originally filed because this class is always in the same global namespace for all projects.

2023-03-20 16:12 UTC, alexrp commented
> The tests themselves prove that no namespace is emitted for C# or VB

But that's expected, right? The PR makes it so that, for C#/VB, a namespace is only emitted if the project explicitly sets `NBGV_ThisAssemblyNamespace` to some non-empty value. For F#, a namespace is indeed always emitted as was the case prior to the PR.

I *could* make it always emit a namespace, but I figured that might be a bad idea for compatibility reasons.

2023-03-20 16:56 UTC, alexrp commented
> If I'm wrong, can you point me to the code that emits the namespace?

Here (and similarly for VB):

https://github.com/dotnet/Nerdbank.GitVersioning/pull/911/files#diff-784868d214d0f8f1823e743bdc0b7b56b4e899e08201e712ccb2bc9e35594977L756-R766

I put the code in those methods out of convenience since for C#/VB it requires opening *and* closing a namespace, unlike F#. (Also, I figured we shouldn't rely on file-scoped namespaces since people might be using older C# versions?) I could add a new pair of `StartThisAssemblyNamespace`/`EndThisAssemblyNamespace` methods if you think that'd be clearer.

2023-03-21 03:29 UTC, alexrp commented
OK, here's take 2, now with tests.

2023-03-27 18:40 UTC, AArnott requested changes
Looks much better. Thank you. Just one small change please.

2023-03-27 18:40 UTC, AArnott commented on test/Nerdbank.GitVersioning.Tests/AssemblyInfoTest.cs
> +    [InlineData("MyCustomNamespace", "MyRootNamespace")]
Can you add one more case here, where *both* inputs are null/empty so that we hit the `AssemblyInfo` namespace case?

2023-03-27 20:20 UTC, alexrp commented on test/Nerdbank.GitVersioning.Tests/AssemblyInfoTest.cs
> +    [InlineData("MyCustomNamespace", "MyRootNamespace")]
The test above this one is testing a few different things, but I believe that specific case is also covered by it?

2023-03-28 22:24 UTC, AArnott approved these changes

2023-03-28 22:25 UTC, merged

2023-03-28 22:25 UTC, AArnott commented
Thanks again.