Enhancement991
dotnet/Nerdbank.GitVersioning pull request #996
Opened 2023-11-09 16:07 UTC by fmacavilca

By default, the `prepare-release` command generates a commit message with the format "Set version to {version}". So with this new option, You can add a prefix or suffix to the default commit message

For example, running the following command on `master`

```
nbgv prepare-release --commit-message-pattern "Custom commit message pattern - {0} custom message"
```

So your commit message is going to be this:

```
Custom commit message pattern - Set version to '1.0' custom message

2023-11-09 16:13 UTC, fmacavilca commented
@dotnet-policy-service agree

2023-11-09 20:04 UTC, FernandoCalmet approved these changes

2023-11-09 20:15 UTC, wchoque approved these changes

2023-11-10 02:57 UTC, AArnott requested changes
I like it. Just a few changes please. The design change idea (about reducing what `{0}` is replaced with) is just an idea. It's at your discretion.

2023-11-10 02:57 UTC, AArnott commented on doc/nbgv-cli.md
> +### Customizing the `prepare-release` commit message
Thank you for the documentation update!
It makes me wonder... maybe when the message is customized, the `{0}` should be replaced with only the version itself, allowing total customization of the message.

2023-11-10 02:57 UTC, AArnott commented on src/nbgv/Program.cs
> +                var commitMessagePattern = new Option<string>("--commit-message-pattern", "Custom pattern to add a prefix or suffix to the default commit message.");
Can you add to the description something to indicate that `{0}` is expected to appear somewhere in the argument?

2023-11-10 02:57 UTC, AArnott commented on src/nbgv/Program.cs
> +            if (AreCurlyBracesBalanced(commitMessagePattern))
Let's not get into the business of manual validation of the message. Let's leave it to `string.Format` and (if we can) catch any exception thrown in order to print the error message and return the error code.

2023-11-15 04:10 UTC, AArnott approved these changes
Thanks for this!

2023-11-15 14:00 UTC, FernandoCalmet approved these changes

2023-11-15 14:05 UTC, choquewilber commented on src/nbgv/Program.cs
> +            InvalidunformattedCommitMessage,
@AArnott I think it should be Invalid`U`nformattedCommitMessage

2023-11-15 14:10 UTC, wchoque commented on src/nbgv/Program.cs
> +            InvalidunformattedCommitMessage,
@AArnott I think it should be Invalid`U`nformattedCommitMessage to follow PascalCase convention

2023-11-15 14:11 UTC, AArnott commented on src/nbgv/Program.cs
> +            InvalidunformattedCommitMessage,
Whoops. That was a search and replace result. Yes, I'll fix.

2023-11-15 14:31 UTC, merged

2023-11-15 14:39 UTC, fmacavilca commented
@AArnott, do you know when it will be published in the new release?

2023-11-16 14:16 UTC, AArnott commented
I can issue a prerelease to nuget.org if that will suffice for you.

2023-11-16 14:40 UTC, fmacavilca commented
Yes, please. It will be great. Thanks

2023-11-16 23:22 UTC, AArnott commented
https://www.nuget.org/packages/Nerdbank.GitVersioning/3.7.48-alpha

2024-05-15 09:23 UTC, ronaldbarendse commented on doc/nbgv-cli.md
> +### Customizing the `prepare-release` commit message
Shouldn't the placeholder be named `{version}` instead, both to be more descriptive and align with the release tag and branch name formats?

The current code also uses `string.Format()` without any validation or exception handling, so any unescaped `{...}` values that are not `{0}` will cause a `FormatException` 😢